#!/usr/bin/env bash
#Script that displays different sentences at the 4th and 8th loops out of the 10 loops of Best School using while, if, elif and else statements
NUMBER=1
while((NUMBER<11));do
	if [ "$NUMBER" -eq 4 ] ;then 
		echo "bad luck"
	elif [ "$NUMBER" -eq 8 ] ;then
		echo "good luck"
	else
		echo "Best School"
	fi
((NUMBER++))
done;
